data_handler:
  label_name:
    - 'Y'
  feature_num:
    - 'X1'
    - 'X2'
    - 'X3'
    - 'X4'
    - 'X5'
    - 'X6'
    - 'X7'
    - 'X8'
    - 'X9'
  feature_cat:
    - 'Z1'
    - 'Z2'
    - 'Z4'
    - 'Z5'
    - 'Z6'
    - 'Z8'
experiment:
  score: 'neg_mean_squared_error'

